POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "test3",
    "password": "test"

}

###
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "username": "test3",
    "email": "test3@mail.com",
    "password": "test"
}


###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token e73d3340b09a18bafd2c2209c5b1c69bb0ad6ab0


###

GET http://127.0.0.1:8000/all_users
Content-Type: application/json
