# Generated by Django 5.0.6 on 2024-05-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('documentNumber', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Bank Data',
                'verbose_name_plural': 'Bank Data',
                'db_table': 'bank_data',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('documentNumber', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Book Data',
                'verbose_name_plural': 'Book Data',
                'db_table': 'book_data',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Conciliation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accountNumber', models.BigIntegerField()),
                ('date', models.DateField()),
                ('bank', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('BankId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliations.bankdata')),
                ('BookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliations.bookdata')),
            ],
            options={
                'verbose_name': 'Conciliation',
                'verbose_name_plural': 'Conciliations',
                'db_table': 'conciliations',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ConciliationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ConciliationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliations.conciliation')),
            ],
            options={
                'verbose_name': 'Conciliation History',
                'verbose_name_plural': 'Conciliation History',
                'db_table': 'conciliation_history',
                'ordering': ['date'],
            },
        ),
    ]
