# Generated by Django 5.0.6 on 2024-05-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdata',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankdata',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankdata',
            name='documentNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankdata',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='documentNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conciliation',
            name='accountNumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conciliation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='conciliation',
            name='bank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conciliation',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conciliationhistory',
            name='ConciliationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conciliations.conciliation'),
        ),
        migrations.AlterField(
            model_name='conciliationhistory',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conciliationhistory',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conciliationhistory',
            name='status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
